version: "3.9"
services:
  back:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    container_name: back
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: db
