# Generated by Django 5.2.1 on 2025-05-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_citysearch_session_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citysearch",
            name="city",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
