# Generated by Django 5.2.1 on 2025-05-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_citysearch_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citysearch",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
